/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-125628-ga5e6c0175a-20260715"
#endif /* AVUTIL_FFVERSION_H */
